name: Build Karmas Client

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: List files
        run: ls -la
      - name: Make gradlew executable
        run: chmod +x ./gradlew || true
      - name: Install Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.8'
      - name: Build with Gradle
        run: gradle build
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: karmas-client-jar
          path: build/libs/*.jar
