name: Build Karmas Client

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v3
      - name: Build
        run: ./gradlew build
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: karmas-client-jar
          path: build/libs/*.jar
